package types;

import moves.MoveType;

import java.util.HashMap;

public class TypeChart {

    private static final HashMap<
            MoveType,
            HashMap<MoveType, Double>
            > chart = new HashMap<>();

    static {

        // NORMAL //
        addEffectiveness(
                MoveType.NORMAL,
                MoveType.GHOST,
                0.0
        );
        addEffectiveness(
                MoveType.NORMAL,
                MoveType.ROCK,
                0.5
        );
        addEffectiveness(
                MoveType.NORMAL,
                MoveType.STEEL,
                0.5
        );

        // FIRE //
        addEffectiveness(
                MoveType.FIRE,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.WATER,
                0.5
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.GRASS,
                2.0
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.ICE,
                2.0
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.BUG,
                2.0
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.ROCK,
                0.5
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.DRAGON,
                0.5
        );
        addEffectiveness(
                MoveType.FIRE,
                MoveType.STEEL,
                2.0
        );

        // WATER //
        addEffectiveness(
                MoveType.WATER,
                MoveType.FIRE,
                2.0
        );
        addEffectiveness(
                MoveType.WATER,
                MoveType.WATER,
                0.5
        );
        addEffectiveness(
                MoveType.WATER,
                MoveType.GRASS,
                0.5
        );
        addEffectiveness(
                MoveType.WATER,
                MoveType.GROUND,
                2.0
        );
        addEffectiveness(
                MoveType.WATER,
                MoveType.ROCK,
                2.0
        );
        addEffectiveness(
                MoveType.WATER,
                MoveType.DRAGON,
                0.5
        );

        // ELECTRIC //
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.WATER,
                2.0
        );
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.ELECTRIC,
                0.5
        );
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.GRASS,
                0.5
        );
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.GROUND,
                0.0
        );
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.FLYING,
                2.0
        );
        addEffectiveness(
                MoveType.ELECTRIC,
                MoveType.DRAGON,
                0.5
        );

        // GRASS //
        addEffectiveness(
                MoveType.GRASS,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.WATER,
                2.0
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.GRASS,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.POISON,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.GROUND,
                2.0
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.FLYING,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.BUG,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.ROCK,
                2.0
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.DRAGON,
                0.5
        );
        addEffectiveness(
                MoveType.GRASS,
                MoveType.STEEL,
                0.5
        );

        // ICE //
        addEffectiveness(
                MoveType.ICE,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.WATER,
                0.5
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.GRASS,
                2.0
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.ICE,
                0.5
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.GROUND,
                2.0
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.FLYING,
                2.0
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.DRAGON,
                2.0
        );
        addEffectiveness(
                MoveType.ICE,
                MoveType.STEEL,
                0.5
        );

        // FIGHTING //
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.NORMAL,
                2.0
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.ICE,
                2.0
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.POISON,
                0.5
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.FLYING,
                0.5
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.PSYCHIC,
                0.5
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.BUG,
                0.5
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.ROCK,
                2.0
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.GHOST,
                0.0
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.STEEL,
                2.0
        );
        addEffectiveness(
                MoveType.FIGHTING,
                MoveType.FAIRY,
                0.5
        );

        // POISON //
        addEffectiveness(
                MoveType.POISON,
                MoveType.GRASS,
                2.0
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.POISON,
                0.5
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.GROUND,
                0.5
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.ROCK,
                0.5
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.GHOST,
                0.5
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.STEEL,
                0.0
        );
        addEffectiveness(
                MoveType.POISON,
                MoveType.FAIRY,
                2.0
        );

        // GROUND //
        addEffectiveness(
                MoveType.GROUND,
                MoveType.FIRE,
                2.0
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.ELECTRIC,
                2.0
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.GRASS,
                0.5
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.POISON,
                2.0
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.FLYING,
                0.0
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.BUG,
                0.5
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.ROCK,
                2.0
        );
        addEffectiveness(
                MoveType.GROUND,
                MoveType.STEEL,
                2.0
        );

        // FLYING //
        addEffectiveness(
                MoveType.FLYING,
                MoveType.ELECTRIC,
                0.5
        );
        addEffectiveness(
                MoveType.FLYING,
                MoveType.GRASS,
                2.0
        );
        addEffectiveness(
                MoveType.FLYING,
                MoveType.FIGHTING,
                2.0
        );
        addEffectiveness(
                MoveType.FLYING,
                MoveType.BUG,
                2.0
        );
        addEffectiveness(
                MoveType.FLYING,
                MoveType.ROCK,
                0.5
        );
        addEffectiveness(
                MoveType.FLYING,
                MoveType.STEEL,
                0.5
        );

        // PSYCHIC //
        addEffectiveness(
                MoveType.PSYCHIC,
                MoveType.FIGHTING,
                2.0
        );
        addEffectiveness(
                MoveType.PSYCHIC,
                MoveType.POISON,
                2.0
        );
        addEffectiveness(
                MoveType.PSYCHIC,
                MoveType.PSYCHIC,
                0.5
        );
        addEffectiveness(
                MoveType.PSYCHIC,
                MoveType.STEEL,
                0.5
        );

        // BUG //
        addEffectiveness(
                MoveType.BUG,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.GRASS,
                2.0
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.FIGHTING,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.POISON,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.FLYING,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.PSYCHIC,
                2.0
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.GHOST,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.STEEL,
                0.5
        );
        addEffectiveness(
                MoveType.BUG,
                MoveType.FAIRY,
                0.5
        );

        // ROCK //
        addEffectiveness(
                MoveType.ROCK,
                MoveType.FIRE,
                2.0
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.ICE,
                2.0
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.FIGHTING,
                0.5
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.GROUND,
                0.5
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.FLYING,
                2.0
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.BUG,
                2.0
        );
        addEffectiveness(
                MoveType.ROCK,
                MoveType.STEEL,
                0.5
        );

        // GHOST //
        addEffectiveness(
                MoveType.GHOST,
                MoveType.NORMAL,
                0.0
        );
        addEffectiveness(
                MoveType.GHOST,
                MoveType.PSYCHIC,
                2.0
        );
        addEffectiveness(
                MoveType.GHOST,
                MoveType.GHOST,
                2.0
        );

        // DRAGON //
        addEffectiveness(
                MoveType.DRAGON,
                MoveType.DRAGON,
                2.0
        );
        addEffectiveness(
                MoveType.DRAGON,
                MoveType.STEEL,
                0.5
        );
        addEffectiveness(
                MoveType.DRAGON,
                MoveType.FAIRY,
                0.0
        );

        // STEEL //
        addEffectiveness(
                MoveType.STEEL,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.WATER,
                0.5
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.ELECTRIC,
                0.5
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.ICE,
                2.0
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.ROCK,
                2.0
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.STEEL,
                0.5
        );
        addEffectiveness(
                MoveType.STEEL,
                MoveType.FAIRY,
                2.0
        );

        // FAIRY //
        addEffectiveness(
                MoveType.FAIRY,
                MoveType.FIRE,
                0.5
        );
        addEffectiveness(
                MoveType.FAIRY,
                MoveType.FIGHTING,
                2.0
        );
        addEffectiveness(
                MoveType.FAIRY,
                MoveType.POISON,
                0.5
        );
        addEffectiveness(
                MoveType.FAIRY,
                MoveType.DRAGON,
                2.0
        );
        addEffectiveness(
                MoveType.FAIRY,
                MoveType.STEEL,
                0.5
        );
    }

    private static void addEffectiveness(MoveType attackType, MoveType targetType, double multiplier) {

        chart.putIfAbsent(attackType,new HashMap<>());

        chart.get(attackType).put(targetType,multiplier);
    }

    public static double getMultiplier(MoveType attackType, MoveType targetType) {

        if (chart.containsKey(attackType)&&chart.get(attackType).containsKey(targetType)) {

            return chart.get(attackType).get(targetType);
        }

        return 1.0;
    }
}
